[package]
name = "kore-pipeline"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
bytes.workspace = true
futures = "0.3"
kore-devtools = { path = "../devtools" }
kore-ipc = { path = "../ipc" }
kore-css = { path = "../css" }
kore-gpu = { path = "../gpu" }
kore-html = { path = "../html" }
kore-js = { path = "../js" }
kore-layout = { path = "../layout" }
kore-net = { path = "../net" }
serde.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["rt"] }
url.workspace = true
